apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: formbricks
  namespace: formbricks
spec:
  chart:
    spec:
      chart: app-template
      version: 0.2.1
      sourceRef:
        kind: HelmRepository
        name: elfhosted
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: formbricks
  values:
    global:
      nameOverride: formbricks
    image:
      registry: ghcr.io
      repository: formbricks/formbricks
      tag: v2.3.0@sha256:9f8976f51659b4dc459d4aed4846043cce2f62dfbdf82d23b75904e1e35e43b6
    securityContext:
      seccompProfile:
        type: RuntimeDefault
      readOnlyRootFilesystem: true
    podSecurityContext:
      seccompProfile:
        type: RuntimeDefault
      # runAsUser: 568
      # runAsGroup: 568
      # fsGroup: 568
    automountServiceAccountToken: false
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        cpu: 1
        memory: 1Gi    
    controller:
      replicas: 1      
    ingress:
      main:
        enabled: false 
    service:
      main:
        enabled: true # necessary for probes
        ports:
          http:
            port: 3000
    persistence:
      config:
        enabled: true
        type: custom
        mountPath: /data/
        volumeSpec:
          persistentVolumeClaim:
            claimName: formbricks    
      tmp: 
        enabled: true
        type: custom
        mountPath: /tmp
        volumeSpec:
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes: [ "ReadWriteOnce" ]
                storageClassName: "topolvm-provisioner-thin"
                resources:
                  requests:
                    storage: 1Gi               
          
